apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Online-Travelling-App"
  description: |
    The customer authorises payment via an online form allowing the business to automatically collect the funds when due. The business' bank and the customer's bank communicate and action the payment request when the payment is due, ensuring the correct amount is debited from the customer and credited to the business.
  links:
    - title: Documentation
      url: https://backstage.io/docs
    - title: Backstage Website
      url: https://backstage.io/
    - title: Blackduck Website
      url: https://github.com/deepan10/backstage-plugin-blackduck  
  annotations:
    flowsource/azure-project-name: SPE - Flowsource-Implementation
    flowsource/azure-repo-name: jaswant_internal_repo
    flowsource/azure-devops-project-key: SPE - Flowsource-Implementation
    backstage.io/techdocs-ref: dir:.
    # cognizant/checkmarx-project-id: CAC_automationenginewindows_v4.3.1-latest
    flowsource/sonarqube-project-key: My-SpringBoot-App
    # flowsource/sonarqube-project-key: SPE_-_Flowsource-Implementation_jaswant_internal_repo_5561c4b5-96c2-4ae4-b6c3-cba9ed8b5278
    flowsource/azure-pipelines: Infra_Automation, jaswant_internal_repo
    flowsource/jenkins-pipelines: Flowsource-demo-pipeline,Test - pipeline
    flowsource/jenkins-pipelines-trigger: Flowsource-demo-pipeline,Test - pipeline
    flowsource/servicenow-configuration-item: ANNIE-IBM
    flowsource/github-repo-owner: sowmyadadi
    flowsource/github-repo-name: sowmyareponew2026
    flowsource/github-host: github.com
    # blackduck/project: automation-center-messageinterface/ver.1
    # flowsource/fis-aws-region: us-east-2
    # flowsource/aws-resiliencehub-appname: demotest
    # flowsource/aws-resiliencehub-region: us-east-2
    # backstage.io/kubernetes-id: flowsource
    # backstage.io/kubernetes-namespace: flwdemo
    # endoflife.date/products: nodejs@18,react@17,python,kubernetes,postgresql
  tags:
    - payment
    - transcation
spec:
  type: service
  system: flowsource-demo
  owner: group:default-group
  lifecycle: Development
#   dependsOn:
#     - component:default/Payment-App-Gateway-System
#     - resource:default/Payment-App-User-Database1
#   providesApis:
#     - Payment-App-Gateway-System
# ---
# apiVersion: backstage.io/v1alpha1
# kind: Resource
# metadata:
#   name: Payment-App-User-Database1
#   description: Database for storing the details
#   annotations:
#     backstage.io/techdocs-ref: dir:.
# spec:
#   type: database
#   owner: group:default-group
#   system: flowsource-demo
# ---
# apiVersion: backstage.io/v1alpha1
# kind: API
# metadata:
#   name: Payment-App-Gateway-System
#   description: The repository contains the BSPlugins integrating the diffrent channels (Web, Skype for business, Cortana, WebEx Teams, MS Teams*, Twilio* & Custom Channels) into HiveCenter Chatops Engine. The interface provides single endpoint for tapping into the features offered part of the I&O automation platform.
#   tags:
#     - node
# spec:
#   type: openapi
#   lifecycle: Development
#   owner: group:default-group
#   system: flowsource-demo
#   definition:
#     $text: './api-info.yaml'
